# Project: Generate Parallel Databases

Key to the definition of differential privacy is the ability to ask the question "When querying a database, if I removed someone from the database, would the output of the query be any different?". Thus, in oder to check this, we must construct what we term "parallel databases" which are simply databases with one entry removed.

In [1]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db = db.type(torch.uint8)
db

tensor([1, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8)

In [2]:
remove_index = 2

In [3]:
def get_parallel_db(db, remove_index):
    return  torch.cat((db[0:remove_index], db[remove_index+1:]))

In [4]:
get_parallel_db(db, 3)

tensor([1, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8)

In [5]:
def get_parallel_dbs(db):
    parallel_dbs = list()
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
    
    return parallel_dbs

In [6]:
len(get_parallel_dbs(db))

5000

In [7]:
def create_db_and_parallels(num_entries):
    db = torch.rand(num_entries) > 0.5
    db = db.type(torch.uint8)
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

In [8]:
create_db_and_parallels(5000)

(tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 [tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
  tensor([1